DATA SEGMENT ;定义数据段
STR1 DB 'HELLO12345'
RESULT1 DB 0
RESULT2 DB 0
DATA ENDS
EXTRA SEGMENT;定义附加段
STR2 DB 'HELLO1&345' ;两串不完全相同
EXTRA ENDS
CODE SEGMENT 
ASSUME DS:DATA,CS:CODE,ES:EXTRA ;说明代码段、数据段
GO: 
	MOV CX,10;第一次忘了置次数
	MOV AX,DATA 
	MOV DS,AX ;给DS赋初值
	MOV AX,EXTRA
	MOV ES,AX;给ES赋初值
	MOV SI,OFFSET STR1;
	MOV DI,OFFSET STR2
	REPE CMPSB
	JZ EQQ;若不完全一样，就不跳转
	DEC SI;恢复到不一样的地方
	MOV BX,SI;传送不一样的字节地址
	MOV [RESULT1],BL ;只有变量才可以用LOW指令
	MOV AL,[SI]
	MOV [RESULT2],AL
	JMP LAST
EQQ: 
	MOV [RESULT1],0;若完全相同，RESULT1置0
LAST:
	MOV AH,4CH
	INT 21H
CODE 	ENDS
		END GO
